language: elixir

otp_release:
  - 18.2
elixir:
  - 1.2.2
  - 1.1.1
sudo: false
script:
  - MIX_ENV=test mix test --no-start --trace
env:
  - MIX_ENV=test
env:
  matrix:
    - POXA_REGISTRY_ADAPTER=gproc
before_script:
  - export PLT_FILENAME=elixir-$TRAVIS_ELIXIR_VERSION-$TRAVIS_OTP_RELEASE.plt
  - wget -O .local.plt https://s3.amazonaws.com/poxa-plt/travis_elixir_plts/$PLT_FILENAME || true
script:
  - mix test
  - mix dialyzer
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
