language: elixir

otp_release:
  - 18.3
  - 19.0
elixir:
  - 1.2.6
  - 1.3.0
sudo: false
env:
  - MIX_ENV=test
env:
  matrix:
    - POXA_REGISTRY_ADAPTER=gproc
before_script:
  - gem install pronto-dialyzer > /dev/null &
  - export PLT_FILENAME=elixir-$TRAVIS_ELIXIR_VERSION-$TRAVIS_OTP_RELEASE.plt
  - wget -O .local.plt https://s3.amazonaws.com/poxa-plt/travis_elixir_plts/$PLT_FILENAME || true
script:
  - MIX_ENV=test mix test --no-start --trace --exclude integration
  - MIX_ENV=test mix test --trace --only integration
  - mix dialyzer -o dialyzer.out && cat dialyzer.out || true
after_script:
  - PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST pronto run -f github_pr -c origin/master
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
